### ISSUE TITLE
Help us add algorithms docs!

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/algorithms#31]
Hi, everyone!

We've created this project, with the main objective or learning and help others to learn as well. We want to create a community or a great website with the documentation for algorithms as well as the implementation is different languages.

Do you know any algorithm implementation in any language, that you wanna share with us? Open a pull request in any of the programming languages available.

Feel free to contribute to updating our site: [allalgorithms.com](https://allalgorithms.com).

Best,
Abraham - @abranhe

**Comment by Jopepato** [comment]
Hello, I would like to document some algorithms, I will be creating a PR for each of them

**Comment by abranhe** [comment]
@Jopepato that would be amazing! Looking forward to merging your PRs.
