### ISSUE TITLE
Help us document algorithms! PRs welcome! 

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/algorithms#47]
I am creating an issue because...
Hi, everyone!

We've created this project, with the main objective or learning and help others to learn as well. We want to create a community or a great website with the documentation for algorithms as well as the implementation is different languages.

Do you know any algorithm implementation in any language, that you wanna share with us? Open a pull request in any of the programming languages available.

Feel free to contribute to updating our site: [allalgorithms.com](https://allalgorithms.com).

Best,
Abraham - @abranhe

**Comment by TheSussex** [comment]
I'd like to know if I can create a python algorithm that fill in blanks in an array with the most recent value in the array. I thought of a number guess algorithm too. I'm quite new to open source so I'll appreciate if I can be pointed in the direction of beginner-friendly projects. Thanks. @abranhe

**Comment by Xyncgas** [comment]
There should be SPA experience, so I don't get scrolled to the top when I click on algorithms
